# Generated by Django 2.2 on 2020-12-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0002_auto_20201201_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pkl',
        ),
    ]
