# Generated by Django 2.2 on 2020-12-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databus',
            name='harga',
            field=models.IntegerField(default=None),
        ),
    ]
