# Generated by Django 2.2 on 2020-12-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databus',
            old_name='nama_bus',
            new_name='title',
        ),
    ]
