# Generated by Django 2.2 on 2020-12-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_auto_20201203_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databus',
            name='title',
        ),
        migrations.AddField(
            model_name='databus',
            name='ac',
            field=models.BooleanField(default=False, verbose_name='ac'),
        ),
        migrations.AddField(
            model_name='databus',
            name='bagasi',
            field=models.BooleanField(default=False, verbose_name='Bagasi'),
        ),
        migrations.AddField(
            model_name='databus',
            name='bantal',
            field=models.BooleanField(default=False, verbose_name='Bantal'),
        ),
        migrations.AddField(
            model_name='databus',
            name='dvd',
            field=models.BooleanField(default=False, verbose_name='DVD/Video'),
        ),
        migrations.AddField(
            model_name='databus',
            name='jml_kursi',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='databus',
            name='judul',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='databus',
            name='kategori',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='databus',
            name='merk_seri_bus',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='databus',
            name='no_plat',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='databus',
            name='sabuk_pengaman',
            field=models.BooleanField(default=False, verbose_name='Sabuk Pengaman'),
        ),
        migrations.AddField(
            model_name='databus',
            name='selimut',
            field=models.BooleanField(default=False, verbose_name='Selimut'),
        ),
        migrations.AddField(
            model_name='databus',
            name='smoking_area',
            field=models.BooleanField(default=False, verbose_name='Smoking Area'),
        ),
        migrations.AddField(
            model_name='databus',
            name='stop_kontak',
            field=models.BooleanField(default=False, verbose_name='Stop Kontak'),
        ),
        migrations.AddField(
            model_name='databus',
            name='tahun_pembuatan',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='databus',
            name='tambahan',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='databus',
            name='toilet',
            field=models.BooleanField(default=False, verbose_name='Toilet'),
        ),
        migrations.AddField(
            model_name='databus',
            name='tv',
            field=models.BooleanField(default=False, verbose_name='TV'),
        ),
        migrations.AddField(
            model_name='databus',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='WIFI'),
        ),
    ]
