# Generated by Django 2.2 on 2020-12-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0003_auto_20201203_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataBus',
        ),
    ]
