# Generated by Django 2.2 on 2020-12-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0003_delete_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='databus',
            name='po_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
