# Generated by Django 2.2 on 2020-12-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0003_databus_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databus',
            name='img',
        ),
    ]
