# Generated by Django 2.2 on 2020-12-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0004_remove_databus_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='databus',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/image/'),
        ),
    ]
