# Generated by Django 2.2 on 2020-12-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0004_delete_databus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default=None, max_length=100)),
                ('merk_seri_bus', models.CharField(default=None, max_length=100)),
                ('tahun_pembuatan', models.DateField(default=None)),
                ('no_plat', models.CharField(default=None, max_length=15)),
                ('kategori', models.CharField(default=None, max_length=100)),
                ('jml_kursi', models.IntegerField(default=None)),
                ('ac', models.BooleanField(default=False, verbose_name='ac')),
                ('dvd', models.BooleanField(default=False, verbose_name='DVD/Video')),
                ('toilet', models.BooleanField(default=False, verbose_name='Toilet')),
                ('stop_kontak', models.BooleanField(default=False, verbose_name='Stop Kontak')),
                ('sabuk_pengaman', models.BooleanField(default=False, verbose_name='Sabuk Pengaman')),
                ('bagasi', models.BooleanField(default=False, verbose_name='Bagasi')),
                ('wifi', models.BooleanField(default=False, verbose_name='WIFI')),
                ('tv', models.BooleanField(default=False, verbose_name='TV')),
                ('bantal', models.BooleanField(default=False, verbose_name='Bantal')),
                ('selimut', models.BooleanField(default=False, verbose_name='Selimut')),
                ('smoking_area', models.BooleanField(default=False, verbose_name='Smoking Area')),
                ('img', models.ImageField(upload_to='static/image/')),
                ('tambahan', models.TextField(default=None)),
            ],
        ),
    ]
