# Generated by Django 2.2.12 on 2020-12-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0005_auto_20201211_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databus',
            name='img',
            field=models.ImageField(blank=True, upload_to='gambar/'),
        ),
    ]
