# Generated by Django 2.2 on 2020-12-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0005_databus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='databus',
            old_name='tahun_pembuatan',
            new_name='tanggal_pembuatan',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='kategori',
        ),
    ]
