# Generated by Django 2.2 on 2020-12-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0006_auto_20201203_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databus',
            name='tanggal_pembuatan',
        ),
    ]
