# Generated by Django 2.2 on 2020-12-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0006_databus_jml_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databus',
            name='kategori',
            field=models.CharField(choices=[('Kecil', 'kecil'), ('Medium', 'medium'), ('Besar', 'besar')], default=None, max_length=10),
        ),
    ]
