# Generated by Django 2.2 on 2020-12-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0007_remove_databus_tanggal_pembuatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databus',
            name='img',
        ),
    ]
