# Generated by Django 2.2 on 2020-12-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0007_postimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='Images',
        ),
    ]
