# Generated by Django 2.2 on 2020-12-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0007_auto_20201208_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databus',
            name='kategori',
            field=models.CharField(choices=[('kecil', 'Kecil'), ('medium', 'Medium'), ('besar', 'Besar')], default=None, max_length=10),
        ),
    ]
