# Generated by Django 2.2 on 2020-12-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0008_remove_databus_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databus',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='bagasi',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='bantal',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='dvd',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='sabuk_pengaman',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='selimut',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='smoking_area',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='stop_kontak',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='toilet',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='tv',
        ),
        migrations.RemoveField(
            model_name='databus',
            name='wifi',
        ),
    ]
