# Generated by Django 2.2 on 2020-12-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0009_auto_20201217_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databus',
            name='harga',
        ),
        migrations.AddField(
            model_name='databus',
            name='harga_12jam',
            field=models.IntegerField(default=500000),
        ),
        migrations.AddField(
            model_name='databus',
            name='harga_fullday',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='databus',
            name='merk_seri_bus',
            field=models.CharField(choices=[('kecil', 'Kecil'), ('medium', 'Medium'), ('besar', 'Besar')], default=None, max_length=100, null=True),
        ),
    ]
