# Generated by Django 2.2 on 2020-12-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0010_auto_20201217_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databus',
            name='merk_seri_bus',
            field=models.CharField(choices=[('Scania', 'Scania'), ('Hino', 'Hino'), ('Mercedez Benz', 'Mercedez Benz'), ('Volvo', 'Volvo'), ('Mitsubishi Fuso', 'Mitsubishi Fuso'), ('Toyota Dyana', 'Toyota Dyana'), ('Zhong Thong', 'Zhong Thong')], default=None, max_length=100, null=True),
        ),
    ]
