# Generated by Django 2.2 on 2020-12-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0010_auto_20201203_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='databus',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengguna.Jenis'),
        ),
    ]
