# Generated by Django 2.2 on 2020-12-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0011_databus_kategori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databus',
            old_name='kategori',
            new_name='kategori_id',
        ),
    ]
