# Generated by Django 2.2 on 2020-12-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0012_auto_20201203_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databus',
            old_name='kategori_id',
            new_name='kategori',
        ),
    ]
