# Generated by Django 2.2 on 2020-12-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0012_auto_20201217_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='t_id',
        ),
    ]
