# Generated by Django 2.2 on 2020-12-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0013_remove_images_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databus',
            name='img',
            field=models.ImageField(blank=True, upload_to='gambaru/'),
        ),
    ]
