# Generated by Django 2.2 on 2020-12-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0016_auto_20201217_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_utama',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/'),
        ),
    ]
