# Generated by Django 2.2 on 2020-12-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_databus_jenis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jenis',
        ),
    ]
