# Generated by Django 2.2 on 2020-12-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0008_auto_20201217_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
