# Generated by Django 2.2 on 2020-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0011_auto_20201217_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(default=None, max_length=100)),
                ('foto_profil', models.ImageField(blank=True, upload_to='gambar/')),
                ('tanggal_berdiri', models.DateField()),
                ('no_tlpn', models.CharField(blank=True, default=False, max_length=15)),
                ('no_hp', models.CharField(default=62, max_length=15)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('provinsi', models.CharField(default=False, max_length=50)),
                ('kabupaten_kota', models.CharField(default=False, max_length=15)),
                ('kecamatan', models.CharField(default=False, max_length=50)),
                ('kode_pos', models.IntegerField(default=False)),
                ('alamat_lengkap', models.TextField(default=None, null=True)),
                ('bio', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='t_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
