# Generated by Django 2.2 on 2020-12-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0014_auto_20201217_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databus',
            name='img',
        ),
    ]
