# Generated by Django 2.2 on 2020-12-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0015_remove_databus_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='gambar/'),
        ),
    ]
